### ISSUE TITLE
Endless tab switching

### ISSUE THREAD

**Issue by rodzyn** [motepair/motepair#17]
I don't know how exactly reproduce it but at some point Atom is starting randomly switching tabs, really fast. We killed all Atom processes, started new sessions and it started happening again.

**Comment by luizbafilho** [comment]
@rodzyn We are aware of that. We started to work on a solution for that. That happens when you close/change tabs too "fast". A workaround would be wait 1-2 seconds before close another tab, until we provide a real solution.

**Comment by luizbafilho** [comment]
@rodzyn Just released a new version. Please update the package to v.0.19.0 and try it again. Let us know if you still have that problem.
