### ISSUE TITLE
Cannot connect to remote server/Deprecation Errors

### ISSUE THREAD

**Issue by kennyheaton** [motepair/motepair#18]
When I try and connect with motepair I get the error message:
Motepair: Could not connect to server.

And Deprecation Cop shows the following error as well:
Are you trying to listen for the 'core:confirm' Atom command with jQuery::on? jQuery::trigger can no longer be used to listen for Atom commands. Please use atom.commands.add instead. See the docs at https://atom.io/docs/api/latest/CommandRegistry#instance-add for details.
Called 12 times
Object.add - /Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:592:14
space-pen-div.<anonymous> - /Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4856:17

**Comment by luizbafilho** [comment]
@kennyheaton Thanks for reporting. I have some questions to you.
- Are you behind a proxy?
- Whats is your Atom Version and Motepair version?

If it's possible, could you change your network and try it again. You could use something like a 3G connection or try it at home. Just to verify if it's not the network that is interfering

**Comment by DarthSim** [comment]
+1. The same issue. Tried cable, vpn, 4g - the same result.

**Comment by luizbafilho** [comment]
@DarthSim and @kennyheaton I'm going to need your help to fix this, because everything is looking fine,   I could connect and everyone I asked for.

I would like to ask you to open the Developer Tools and try to connect again. To do that, just press:
- Ctrl+Alt+I - Linux
- Cmd+Opt+I - Mac OS

Let me know if you see any error or warnings.

**Comment by DarthSim** [comment]
Got this: `Error: socket hang up {code: "ECONNRESET", stack: (...), message: "socket hang up"}` on `lib/main.coffee:123`

**Comment by DarthSim** [comment]
This is strange, but I can't even connect to the local motepair server.

**Comment by luizbafilho** [comment]
@DarthSim  What is the motepair's version, Atom's version and your OS?

**Comment by DarthSim** [comment]
I unchecked "Secure connection" and everything went just fine. Thanks for your work!

Mac OS X 10.10.3, Atom 0.190.0, motepair 0.19.0

**Comment by luizbafilho** [comment]
@DarthSim Thanks. @kennyheaton  Are you with Secure Connection checked too?

**Comment by kennyheaton** [comment]
I did not have Secure Connection checked. I was at work at the time on the corp network. My coworker was able to connection on the same network. I am not home and connection works fine for me also.

I am still getting the above Deprecation Cop error plus this one

TextEditor::on is deprecated. Use documented event subscription methods instead.
Called 1 timeCreate Issue on motepair repo
TextEditor.on - /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3038:11
<unknown> - /Users/kheaton/.atom/packages/motepair/lib/event_handler.coffee:104:13

Atom is version 0.190.0
Motepair is version 0.19.0

**Comment by luizbafilho** [comment]
@kennyheaton We updated the package to remove the deprecated code. Please check it out.
