### ISSUE TITLE
Atom crashes when starting a session. Ubuntu 14.10 x64

### ISSUE THREAD

**Issue by s0r00t** [motepair/motepair#22]
Hello,
I've tried to use motepair today, but when starting a session, Atom crashes. 
I can't manage to get any error logs.
I'm on Ubuntu 14.10, 64 bits.

Thanks,

**Comment by luizbafilho** [comment]
@s0r00t Which version is your atom and motepair and this is the first time you use it?

**Comment by s0r00t** [comment]
It's the first time I use motepair.
Atom v 0.194
Latest motepair from atom.io

**Comment by luizbafilho** [comment]
Once a friend had that problem too. Uninstalling and installing the Atom worked.  Please try it out.

**Comment by s0r00t** [comment]
This is a rather hard solution. Anyways, I'll try it out, and update this comment.

**Comment by s0r00t** [comment]
Nothing changed. It might be a problem with another package?

**Comment by instantink-ia** [comment]
I investigated the code, trying to find something that could crash, but wasn't able to. I use Ubuntu 14.10, my coworkers too, and we had no problem.

I will try to figure out where Atom saves logs of crashes.

**Comment by s0r00t** [comment]
I'm trying to get logs.
Somehow, it worked once. Retried, and it crashed.

**Comment by s0r00t** [comment]
Okay, so I got this dump file, that appeared briefly in /tmp/Atom Crashes.
https://mega.co.nz/#!w8Iz0CJT!jrf6vQd3xEHfnR1Mdgz3LamRxQLRUVUprZ-nEROBN3o

**Comment by NogradThGin** [comment]
Hi, same for me, i'm under Ubuntu 14.10 x64, actually i'm not able to start a session. I'll try to reinstall and edit this message for more informations

Edit: I tried to reinstall Atom Editor, i tryed to wipe my ~/.atom and retry an installation by compile the program from sources. But without any success for motepair

**Comment by danieltdt** [comment]
Same here... but it seems a problem with `ws` package.
This is what happens when I try to debug the coredumped

```
Core was generated by `/usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=-'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe717532011 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/daniel/.atom/packages/motepair/node_modules/ws/build/Release/bufferutil.node
[Current thread is 1 (Thread 0x7fe73b978980 (LWP 2989))]
(gdb)
```

The error

```
#0  0x00007fe717532011 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/daniel/.atom/packages/motepair/node_modules/ws/build/Release/bufferutil.node
```

has already been reported[[1]](https://github.com/websockets/bufferutil/issues/1)[[2]](https://github.com/websockets/ws/issues/448) and probably fixed[[3]](https://github.com/websockets/ws/issues/385#issuecomment-73850769). Please update `ws` dependency version so we can try this out.

**Comment by luizbafilho** [comment]
thanks @danieltdt for pointing out. I just updated the package. Please check it out and let me know if that fix the bug.

**Comment by danieltdt** [comment]
It seems ok now! Thanks :D
