### ISSUE TITLE
Sessions not removed properly? 

### ISSUE THREAD

**Issue by peteruithoven** [motepair/motepair#25]
When switching between sessions id's it will open multiple sessions. 
Steps: 
1. Start Atom
2. Connect to Session ID: a
3. Disconnect
4. Connect to Session ID: b

![motepair sessions issue](https://cloud.githubusercontent.com/assets/523210/8056027/ad6847c2-0ea4-11e5-8931-5817649d2db2.gif)

Maybe all the old / existing sessions aren't removed when connecting to a new id? 

Otherwise, really awesome project!

**Comment by luizbafilho** [comment]
Thanks @peteruithoven, that will be fixed in the next versions, it is just a view problem.

**Comment by peteruithoven** [comment]
Ah alright, great! 
But then I'm still experiencing another issue. I'll report back when I can reproduce it.
