### ISSUE TITLE
Gravatar is not displayed when remote typing

### ISSUE THREAD

**Issue by gangseok514** [motepair/motepair#29]
As you know,
Gravatar is only displayed remote user move cursor not typing.
I think it should be displayed in typing case.

onDidChangeCursorPosition event will be triggered in below case as I know
1. If I cursor move
2. If remote user's input affects my cursor

But sending cursor data to server happens only cursor move(not typing)

I think If you replace the below code to the next, it will work properly.

return if event.textChanged
to
return unless @localChange or (not @localChange and not event.textChanged)

explain this,
If I'm typing, sends data
Or if I'm not typing but text has not been changed, sends data(only cursor move)
(onDidChangeCursorPosition won't be triggered if remote user's input not affects mine)

**Comment by gangseok514** [comment]
above suggested logic has critical problem(handling duplicated cursor and op). I'll find another solution. sorry :)

**Comment by luizbafilho** [comment]
@gangseok514 thanks for pointing out. Please feel free to open a PR with this fix, I would be happy to approve it.

**Comment by luizbafilho** [comment]
Done in #32
