### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by abourget** [motepair/motepair#44]
Couldn't we take a couple of pages from the `floobits` playbook, and wire motepair within Emacs ? and other editors ?

**Comment by timofonic** [comment]
NeoVim too?


Is this alive? :/

**Comment by luizbafilho** [comment]
Hi @abourget that would not be easy, it requires building a compatible client to [Sharejs](https://github.com/share/ShareJS)

@timofonic the same as for emacs, and it's almost alive, I'm quite busy dedicating my whole time to another Opensource project. Maybe in a few months, I'll give more love to motepair.

**Comment by TheNotary** [comment]
Doesn't vim and emacs already live in the terminal so you can pair with them with simple ssh + tmux?
