### ISSUE TITLE
Wrong path Windows, Ubuntu

### ISSUE THREAD

**Issue by Grotax** [motepair/motepair#50]
Atom: `1.16.0`
motepair: `0.23.0`

Client 1: Windows 10, Client 2: Ubuntu 16.04
1) Add the same project folder on both clients
2) Start motepair session on client 1 and connect client 2
3) Open a file on one of the clients
4) file is open on both machines

Problem:
Only the client that opened the file has the correct path and can show the file.
The other client shows an empty file.

Example 1 open with Windows Client
Path on Windows: `C:\Users\Grotax\git\TestProject\Afolder\Afile.ext`
Path on Linux: `/home/grotax/git/TestProject/undefined/Afolder\Afile.ext`

Example 2 open with Linux Client
Path on Windows: `C:\Users\Grotax\git\TestProject\undefined\Afolder\Afile.ext`
Path on Linux: `/home/grotax/git/TestProject/Afolder/Afile.ext`

If you change your active tab back and forth new clients get created:
`C:\Users\Grotax\git\TestProject\undefined\undefined\Afolder\Afile.ext`

Let me know if you need more info.

**Comment by luizbafilho** [comment]
Sorry to say that, but I have no windows machine available to help me develop that. But I could approve a Pull Request a soon as you provide one.
