### ISSUE TITLE
This is the best one out there ATM!

### ISSUE THREAD

**Issue by kilianc** [motepair/motepair#6]
Remote cursor and selection is amazing!
I would like to build a slack integration using `/pair` command for this

**Comment by jeduan** [comment]
:+1:

**Comment by luizbafilho** [comment]
Kilian,

We are happy you apreciate our work. We are now, implementing the secure connection, and the next thing will be the peers indication, pretty much like google docs.

Please, feel free to suggest any feature. We are willing to build the best tool we can. :smile: 

Luiz Filho

**Comment by kilianc** [comment]
@luizbafilho great! Why isn't this backend agnostic? I think coupling it with a specific server is a turn off. I think it should be pluggable on pubnub / pusher / firebase and all the similar.

**Comment by luizbafilho** [comment]
@kilianc because we rely on a lib called [Share.js](http://sharejs.org/) which enables a very reliable concurrent editing using Operational Transformation algorithm. We've started without it, but we had lots of problems with inconsistent states between clients
