### ISSUE TITLE
Show name + gravatar on the cursor

### ISSUE THREAD

**Issue by kilianc** [motepair/motepair#9]
it would be super cool!

**Comment by kilianc** [comment]
holy guacamole!!!!!! can't wait to test it!

**Comment by luizbafilho** [comment]
@kilianc go ahead and test it. You just need to setup your email at motepair settings. I've just released the version 0.16 with the gravatar feature.

@mvallerie check it out too.

**Comment by mvallerie** [comment]
Just tested it with two Atoms on the same machine. Works really well :). I'll test it with a remote friend tonight.
